# Generated by Django 5.0 on 2023-12-24 11:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_employee"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
